"""
Pre-build script — automatically increment the build number on every compile.

  build_number.txt  — plain integer, committed to source control
  src/build_number.h — auto-generated, listed in .gitignore
"""

Import("env")  # noqa: F821  (PlatformIO injects this)
import os

project_dir = env["PROJECT_DIR"]  # noqa: F821
counter_file = os.path.join(project_dir, "build_number.txt")
header_file  = os.path.join(project_dir, "src", "build_number.h")

# ── Read and increment ──────────────────────────────────────────────────────
try:
    with open(counter_file, "r") as f:
        build_num = int(f.read().strip())
except (FileNotFoundError, ValueError):
    build_num = 0

build_num += 1

# ── Persist the new counter ─────────────────────────────────────────────────
with open(counter_file, "w") as f:
    f.write(str(build_num) + "\n")

# ── Emit the generated header ───────────────────────────────────────────────
with open(header_file, "w") as f:
    f.write("// Auto-generated by scripts/increment_build.py — do not edit\n")
    f.write("#pragma once\n")
    f.write(f"#define BUILD_NUMBER     {build_num}\n")
    f.write(f'#define BUILD_NUMBER_STR "{build_num}"\n')

print(f"Build number: {build_num}")
